version: '3'

services:
  main:
    container_name: calalog-movies
    build: .
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports :
      - '8000:8000'
    command: npm run start
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env.development
    environment:
      PG_DATA : /var/lib/postgresql/data
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:

